project_name: webnavix
project_dir: ${oc.env:PROJECT_DIR}
seed: 123

data:
  num_proc: 8
  split_path: ${project_dir}/wl_data/splits.json
  base_dir: ${project_dir}/wl_data/demonstrations/

candidates:
  k: 10
  build_path: ${project_dir}/wl_data/candidates/${build.split}.jsonl
  train_path: ${project_dir}/wl_data/candidates/${train.split}.jsonl
  eval_path: ${project_dir}/wl_data/candidates/${eval.split}.jsonl

model:
  name: nitic-nlp-team/webnavix-ai-tools
  base_name: nitic-nlp-team/webnavix-llama-base
  save_dir: ${project_dir}/checkpoints/${project_name}/${model.name}
  max_inp_len: null
  max_out_len: 256
  use_rope: True
  use_flash_attention_2: True
  moe: False
  freeze:
    use: True
    trainable_layers:
      - gate_proj
      - up_proj
      - down_proj

build:
  split: train
  include_output_target: True

train:
  split: train
  domain: AI_Tools
  num_epochs: 3
  learning_rate: 5e-5
  batch_size_per_device: 16
  gradient_accumulation_steps: 1
  gradient_checkpointing: True
  max_grad_norm: 1.0
  optim: adamw_torch
  weight_decay: 0.0
  scheduler: linear
  warmup_steps: 0
  warmup_ratio: 0.0
  accelerate:
    use: False
  qlora:
    use: False
    r: 256
    alpha: 256
    dropout: 0.05
    bias: none
    target_modules:
      - embed_tokens
      - q_proj
      - k_proj
      - v_proj
      - o_proj
      - gate_proj
      - up_proj
      - down_proj
      - lm_head

merge:
  num_experts_per_tok: 2
  experts:
    - expert_name: ai-tools-expert
      model_id: nitic-nlp-team/webnavix-llama-ai-tools
    - expert_name: booking-expert
      model_id: nitic-nlp-team/webnavix-llama-booking
    - expert_name: composing-expert
      model_id: nitic-nlp-team/webnavix-llama-composing
    - expert_name: information-lookup-expert
      model_id: nitic-nlp-team/webnavix-llama-information-lookup
    - expert_name: shopping-expert
      model_id: nitic-nlp-team/webnavix-llama-shopping
    - expert_name: social-interaction-expert
      model_id: nitic-nlp-team/webnavix-llama-social-interaction
    - expert_name: summarizing-expert
      model_id: nitic-nlp-team/webnavix-llama-summarizing
    - expert_name: task-management-expert
      model_id: nitic-nlp-team/webnavix-llama-task-management
    - expert_name: shared-expert
      model_id: nitic-nlp-team/webnavix-llama-shared
  router_layers:
    - gate_proj
    - up_proj
    - down_proj

eval:
  split: valid
  domain: AI_Tools
  batch_size_per_device: 16
  gradient_accumulation_steps: 1
  result_dir: ${project_dir}/results/${project_name}/${eval.split}/${model.name}
  load_from_save_dir: True

huggingface:
  token: ${oc.env:HF_TOKEN}

wandb:
  project: ${oc.env:WANDB_PROJECT}
  key: ${oc.env:WANDB_API_KEY}

hydra:
  run:
    dir: ${project_dir}/logs/${project_name}/${hydra.job.name}/${now:%Y-%m-%d-%H:%M:%S}
  sweep:
    dir: ${hydra.run.dir}
  job:
    chdir: False
  verbose: INFO
